services:

  smarterp-prod:
    image: 9988496141/smarterp:1.0
    container_name: smarterp-prod
    ports:
      - "8082:80"
    depends_on:
      database-prod:
        condition: service_started
    restart: unless-stopped
    networks:
      - prod_network

  database-prod:
    image: mysql:8.0
    container_name: smarterp-prod-db
    environment:
      MYSQL_DATABASE: smarterp
      MYSQL_USER: smarterp
      MYSQL_PASSWORD: SmartERP@123
      MYSQL_ROOT_PASSWORD: SmartERP@123
    volumes:
      - smarterp_prod_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - prod_network

volumes:
  smarterp_prod_data:
    name: smarterp_prod_data

networks:
  prod_network:
    name: smarterp_prod_network