services:

  smarterp-test:
    image: 9988496141/smarterp:1.1
    container_name: smarterp-test
    ports:
      - "8081:80"
    depends_on:
      database-test:
        condition: service_started

  database-test:
    image: mysql:8.0
    container_name: smarterp-test-db
    environment:
      MYSQL_DATABASE: smarterp_test
      MYSQL_USER: smarterp
      MYSQL_PASSWORD: SmartERP@123
      MYSQL_ROOT_PASSWORD: SmartERP@123
    volumes:
      - smarterp_test_data:/var/lib/mysql
    restart: unless-stopped

volumes:

  smarterp_test_data:
    name: smarterp_test_data